### PR TITLE
add CodeAlerts page

### PR DESCRIPTION
**Pull request by nicomwong**
basically copied DependabotAlerts page

### CODE REVIEW

**Comment by chrisyang365** [comment]
can you include a screen recording of you demoing your new component?

**Comment by nicomwong** [comment]
https://user-images.githubusercontent.com/24986889/152881553-f4fd6780-ce17-4288-a190-003ffccf845b.mov

need to test with existent code alerts

also, there's no button in this PR so i go to the link manually

**Comment by chrisyang365** [comment]
You can preload some dummy data CodeAlerts via the Rails console. Also, you should probably add some way to navigate to your CodeAlerts component on the Repos page

**Comment by nicomwong** [comment]
> You can preload some dummy data CodeAlerts via the Rails console.

oh yes, i can. i'll try that

> Also, you should probably add some way to navigate to your CodeAlerts component on the Repos page

oh ya, i have another branch with the button. want me to just merge it into this branch? it's branch `add-code-alerts-button`

**Comment by chrisyang365** [comment]
yeah include the button in this PR please

**Pull request merged**
